title: "Liu Yu's Homepage"
page-top-title: "Liu Yu"
top-section-bg-text: "Be what you wanna be"
home-subtitle: "Liu Yu&ensp;|&ensp;Yulia2233"
copyright-text: '&copy; Liu Yu 2024-2026. All Rights Reserved.'
